### ISSUE TITLE
Cannot launch greetings-service in VS Code from Spring Boot dashboard

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/fuse-springboot-circuit-breaker-booster#38]
I changed port in application.properties.
I launched the name-service from the spring-boot-dashboard (successfully)
I try to launch the greetings-service from Spring-Boot Dashboard, it is failign with this error:

```
  .   ____          _            __ _ _

 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \

( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \

 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )

  '  |____| .__|_| |_|_| |_\__, | / / / /

 =========|_|==============|___/=/_/_/_/

 :: Spring Boot ::       (v1.5.13.RELEASE)



2018-11-08 14:45:07.088  INFO 49484 --- [           main] com.redhat.fuse.boosters.cb.Application  : Starting Application on DESKTOP-9NT300B with PID 49484 (C:\ws\workingDirectoryForTest\test-circuitBreaker-withFixedSpringbootdashboard\fuse-springboot-circuit-breaker-booster\greetings-service\target\classes started by Aurelien Pupier in C:\ws\workingDirectoryForTest\test-circuitBreaker-withFixedSpringbootdashboard\fuse-springboot-circuit-breaker-booster)

2018-11-08 14:45:07.091  INFO 49484 --- [           main] com.redhat.fuse.boosters.cb.Application  : No active profile set, falling back to default profiles: default

2018-11-08 14:45:07.175  INFO 49484 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@7c0c77c7: startup date [Thu Nov 08 14:45:07 CET 2018]; root of context hierarchy

2018-11-08 14:45:08.136  INFO 49484 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Overriding bean definition for bean 'servletRegistrationBean' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.apache.camel.component.hystrix.springboot.HystrixMappingAutoConfiguration; factoryMethodName=servletRegistrationBean; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/apache/camel/component/hystrix/springboot/HystrixMappingAutoConfiguration.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.apache.camel.component.servlet.springboot.ServletMappingAutoConfiguration; factoryMethodName=servletRegistrationBean; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/apache/camel/component/servlet/springboot/ServletMappingAutoConfiguration.class]]

2018-11-08 14:45:09.238  INFO 49484 --- [           main] org.xnio                                 : XNIO version 3.3.8.Final

2018-11-08 14:45:09.253  INFO 49484 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.3.8.Final

2018-11-08 14:45:09.295  WARN 49484 --- [           main] io.undertow.websockets.jsr               : UT026009: XNIO worker was not set on WebSocketDeploymentInfo, the default worker will be used

2018-11-08 14:45:09.295  WARN 49484 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used

2018-11-08 14:45:09.321  INFO 49484 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext

2018-11-08 14:45:09.321  INFO 49484 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 2152 ms

2018-11-08 14:45:09.357  WARN 49484 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hystrixEventStreamServlet' defined in com.redhat.fuse.boosters.cb.Application: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.ServletRegistrationBean]: Factory method 'servletRegistrationBean' threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/commons/lang/text/StrLookup

2018-11-08 14:45:09.372  INFO 49484 --- [           main] utoConfigurationReportLoggingInitializer : 



Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.

2018-11-08 14:45:09.381 ERROR 49484 --- [           main] o.s.boot.SpringApplication               : Application startup failed



org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hystrixEventStreamServlet' defined in com.redhat.fuse.boosters.cb.Application: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.ServletRegistrationBean]: Factory method 'servletRegistrationBean' threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/commons/lang/text/StrLookup

	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:137) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537) ~[spring-context-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at com.redhat.fuse.boosters.cb.Application.main(Application.java:21) [classes/:na]

Caused by: java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hystrixEventStreamServlet' defined in com.redhat.fuse.boosters.cb.Application: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.ServletRegistrationBean]: Factory method 'servletRegistrationBean' threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/commons/lang/text/StrLookup

	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:241) ~[undertow-servlet-1.4.25.Final.jar:1.4.25.Final]

	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.createDeploymentManager(UndertowEmbeddedServletContainerFactory.java:412) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.getEmbeddedServletContainer(UndertowEmbeddedServletContainerFactory.java:234) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:164) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:134) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	... 8 common frames omitted

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hystrixEventStreamServlet' defined in com.redhat.fuse.boosters.cb.Application: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.ServletRegistrationBean]: Factory method 'servletRegistrationBean' threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/commons/lang/text/StrLookup

	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1181) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1075) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:234) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:215) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.addServletContextInitializerBeans(ServletContextInitializerBeans.java:91) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.<init>(ServletContextInitializerBeans.java:79) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.getServletContextInitializerBeans(EmbeddedWebApplicationContext.java:241) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.selfInitialize(EmbeddedWebApplicationContext.java:228) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.access$000(EmbeddedWebApplicationContext.java:89) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext$1.onStartup(EmbeddedWebApplicationContext.java:213) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory$Initializer.onStartup(UndertowEmbeddedServletContainerFactory.java:723) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:192) ~[undertow-servlet-1.4.25.Final.jar:1.4.25.Final]

	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:174) ~[undertow-servlet-1.4.25.Final.jar:1.4.25.Final]

	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42) ~[undertow-servlet-1.4.25.Final.jar:1.4.25.Final]

	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) ~[undertow-servlet-1.4.25.Final.jar:1.4.25.Final]

	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:239) ~[undertow-servlet-1.4.25.Final.jar:1.4.25.Final]

	... 12 common frames omitted

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.ServletRegistrationBean]: Factory method 'servletRegistrationBean' threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/commons/lang/text/StrLookup

	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	... 34 common frames omitted

Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang/text/StrLookup

	at com.netflix.config.ConfigurationManager.getConfigInstance(ConfigurationManager.java:125) ~[archaius-core-0.4.1.jar:na]

	at com.netflix.config.DynamicPropertyFactory.getInstance(DynamicPropertyFactory.java:263) ~[archaius-core-0.4.1.jar:na]

	at com.netflix.hystrix.contrib.metrics.eventstream.HystrixMetricsStreamServlet.<clinit>(HystrixMetricsStreamServlet.java:55) ~[hystrix-metrics-event-stream-1.5.12.jar:1.5.12]

	at com.redhat.fuse.boosters.cb.Application.servletRegistrationBean(Application.java:26) [classes/:na]

	at com.redhat.fuse.boosters.cb.Application$$EnhancerBySpringCGLIB$$23c4b82a.CGLIB$servletRegistrationBean$0(<generated>) ~[classes/:na]

	at com.redhat.fuse.boosters.cb.Application$$EnhancerBySpringCGLIB$$23c4b82a$$FastClassBySpringCGLIB$$ebdecf1a.invoke(<generated>) ~[classes/:na]

	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) ~[spring-context-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	at com.redhat.fuse.boosters.cb.Application$$EnhancerBySpringCGLIB$$23c4b82a.servletRegistrationBean(<generated>) ~[classes/:na]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]

	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	... 35 common frames omitted

Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.text.StrLookup

	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_171]

	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_171]

	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_171]

	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_171]

	... 49 common frames omitted
```

**Comment by apupier** [comment]
note: it is working well if i launch mvn spring-boot:run from terminal inside VS Code

**Comment by apupier** [comment]
as it is working from command-line it should be an issue in VS Code SpringBoot dashboard, I reported https://github.com/Microsoft/vscode-spring-boot-dashboard/issues/52

**Comment by apupier** [comment]
it comes from the fact that greetings-service is failing when launched with latest releases of Maven.
I tried from command-line
- 3.3.9 --> working
- 3.5.3 --> not working
- 3.6.0 --> not working

VS Code is relying on Eclipse m2e which is embedding at least a 3.5.x version

**Comment by apupier** [comment]
seems more complicated as it is working for some people and CI job is using Maven 3.5.4 https://fusesource-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/JBoss Fuse 7.0/job/fuse-boosters/job/fuse-springboot-circuit-breaker-booster

16:44:50 Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z)

**Comment by apupier** [comment]
there was an artefact corrupted commons-configuration in my .m2

I don't understand why it was working from command-line with Maven 3..3.9 only. Or it was in a format understandable only with Maven 3.3.9?
